= Async parsing [[AsyncParsing]]

NOTE: The parallel parser is also an async parser. But for the most users the parallel
parser adds too much overhead.

If you want to write parsers to run in Javascript environments, then async operations are the norm. The async
parser is a version of the parser were you can return `core.async` channels from the readers instead of raw
values. This allows for the creation of parsers that do network requests or any other async operation.
The async parser is still semantically a *serial* parser, and it will have the same flow characteristics
of the regular parser (the order or resolution is preserved).

To write an async parser we use the `p/async-parser` function. Here is an example:

[source,clojure]
----
include::example$com/wsscode/pathom/book/async/intro.cljs[]
----

Try the example:

++++
<div x-app="interactive-parser" data-parser="async.intro" class="loader">
[:foo :async-info]
</div>
<div class="space"></div>
++++

The core plugins work normally with the async parser, so error and profiling will work as expected.

== Error propagation

When an exception occurs inside a `core.async` channel the error is triggered as part of the channel exception handler.
That doesn't compose very well and for the parser it's better if we have something more like the async/await
pattern available within the JS environments. Pathom provides some macros to facilitate this; instead of using
`go` and `<!`, use the provided `go-catch` and `<?` macros, as shown in the following example:

[source,clojure]
----
include::example$com/wsscode/pathom/book/async/error_propagation.cljs[]
----

++++
<div x-app="interactive-parser" data-parser="async.error-propagation" class="loader">
[:foo :async-info :async-error]
</div>
<div class="space"></div>
++++

Use `com.wsscode.common.async-clj` for Clojure and `com.wsscode.common.async-cljs` for ClojureScript. If you are writing a
cljc file, use the following:

[source,clojure]
----
[#?(:clj  com.wsscode.common.async-clj
    :cljs com.wsscode.common.async-cljs)
 :refer [go-catch <?]]
----

== JS Promises

In JS world most of the current async responses come as promises, you can use the `<!p` macro to read from promises
inside the `go` blocks as if they were channels. Example:

[source,clojure]
----
include::example$com/wsscode/pathom/book/async/js_promises.cljs[]
----

++++
<div x-app="interactive-parser" data-parser="async.js-promises" class="loader">
[:dog.ceo/random-dog-url]
</div>
<div class="space"></div>
++++
