= Parsers

Parsers are at the core of what Pathom does. This section explains how Pathom parsers
accomplish this responsibility and describes how they work.

== The parser job

Every EQL transaction is a vector, this means that, by definition, an EQL transaction is
a collection of things. The parser's job is to walk this collection, figures the value
of each requested entry and return a map with them.

In case of Pathom parsers they also have a distinction between `read` and `mutate`, when
the parser is built those are provided separate.

I may look like a simple task, but it can get quite complicated depending on how you
intend to coordinate that processing. Pathom provides a few built-in parsers in two
main categories:

* xref:core/parsers/serial.adoc[Serial Parsers]: these parsers will process each query
attribute one at time, they work in simple ways and add only a small overhead.
* xref:core/parsers/parallel.adoc[Parallel Parser]: the parallel parser defines some special semantics oriented to support processing multiple
attributes at the same time; when combined with the xref:connect.adoc[Connect parallel reader],
they provide fully automated parallel fetching orchestration.
