(ns com.wsscode.fulcro.reakit
  (:refer-clojure :exclude [list])
  (:require ["reakit" :as rk]
            [fulcro.client.primitives :as fp]
            [fulcro.client.localized-dom :as dom]))

(defn wrap [component]
  (fn [& args]
    (if (keyword? (first args))
      (dom/macro-create-element component (next args) (first args))
      (dom/macro-create-element component args))))

(def arrow (wrap rk/Arrow))
(def backdrop (wrap rk/Backdrop))
(def base (wrap rk/Base))
(def block (wrap rk/Block))
(def blockquote (wrap rk/Blockquote))
(def box (wrap rk/Box))
(def button (wrap rk/Button))
(def card (wrap rk/Card))
(def code (wrap rk/Code))
(def divider (wrap rk/Divider))
(def field (wrap rk/Field))
(def fit (wrap rk/Fit))
(def flex (wrap rk/Flex))
(def grid (wrap rk/Grid))
(def grid-item (wrap rk/Grid.Item))
(def group (wrap rk/Group))
(def group-item (wrap rk/Group.Item))
(def heading (wrap rk/Heading))
(def hidden (wrap rk/Hidden))
(def hidden-container (wrap rk/HiddenContainer))
(def hidden-hide (wrap rk/HiddenHide))
(def hidden-show (wrap rk/HiddenShow))
(def hidden-toggle (wrap rk/HiddenToggle))
(def image (wrap rk/Image))
(def inline (wrap rk/Inline))
(def inline-block (wrap rk/InlineBlock))
(def inline-flex (wrap rk/InlineFlex))
(def input (wrap rk/Input))
(def label (wrap rk/Label))
(def link (wrap rk/Link))
(def list (wrap rk/List))
(def list-item (wrap rk/ListItem))
(def navigation (wrap rk/Navigation))
(def overlay (wrap rk/Overlay))
(def overlay-container (wrap rk/OverlayContainer))
(def overlay-hide (wrap rk/OverlayHide))
(def overlay-show (wrap rk/OverlayShow))
(def overlay-toggle (wrap rk/OverlayToggle))
(def paragraph (wrap rk/Paragraph))
(def perpendicular (wrap rk/Perpendicular))
(def popover (wrap rk/Popover))
(def popover-arrow (wrap rk/PopoverArrow))
(def popover-container (wrap rk/PopoverContainer))
(def popover-hide (wrap rk/PopoverHide))
(def popover-show (wrap rk/PopoverShow))
(def popover-toggle (wrap rk/PopoverToggle))
(def shadow (wrap rk/Shadow))
(def sidebar (wrap rk/Sidebar))
(def sidebar-container (wrap rk/SidebarContainer))
(def sidebar-hide (wrap rk/SidebarHide))
(def sidebar-show (wrap rk/SidebarShow))
(def sidebar-toggle (wrap rk/SidebarToggle))
(def step (wrap rk/Step))
(def step-container (wrap rk/StepContainer))
(def step-hide (wrap rk/StepHide))
(def step-next (wrap rk/StepNext))
(def step-previous (wrap rk/StepPrevious))
(def step-show (wrap rk/StepShow))
(def step-toggle (wrap rk/StepToggle))
(def table (wrap rk/Table))
(def tabs (wrap rk/Tabs))
(def tabs-container (wrap rk/TabsContainer))
(def tabs-next (wrap rk/TabsNext))
(def tabs-panel (wrap rk/TabsPanel))
(def tabs-previous (wrap rk/TabsPrevious))
(def tabs-tab (wrap rk/TabsTab))
(def tooltip (wrap rk/Tooltip))
